/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Casilla;

/**
 *
 * @author ecast
 */
public class CasillaPanel extends javax.swing.JPanel {

    public Casilla casilla;
    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }

    public void setCasilla(Casilla casilla, int numCasilla){
       this.numCasilla.setText("");
       this.nombre.setText("");
       impuesto.setText("");
       sorpresa.setText("");
       this.casilla = casilla;
       this.numCasilla.setText(Integer.toString(numCasilla));
       nombre.setText(casilla.getNombre());
       if (casilla.getImporte() > 0)
            impuesto.setText(Float.toString(casilla.getImporte()));
        if (casilla.getSorpresa() != null)
            sorpresa.setText(casilla.getSorpresa().toString());
        //setVisible(true);
        this.repaint();
        this.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnumcasilla = new javax.swing.JLabel();
        numCasilla = new javax.swing.JTextField();
        cnombre = new javax.swing.JLabel();
        cimpuesto = new javax.swing.JLabel();
        csorpresa = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        impuesto = new javax.swing.JTextField();
        sorpresa = new javax.swing.JTextField();

        cnumcasilla.setText("Casilla");
        cnumcasilla.setEnabled(false);

        numCasilla.setText("numCasilla");
        numCasilla.setEnabled(false);
        numCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCasillaActionPerformed(evt);
            }
        });

        cnombre.setText("Nombre");
        cnombre.setEnabled(false);

        cimpuesto.setText("Impuesto");
        cimpuesto.setEnabled(false);

        csorpresa.setText("Sorpresa");
        csorpresa.setEnabled(false);

        nombre.setText("nombre");
        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        impuesto.setText("Impuesto");
        impuesto.setEnabled(false);

        sorpresa.setText("Sorpresa");
        sorpresa.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(csorpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sorpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cimpuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnombre)
                            .addComponent(cnumcasilla))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnumcasilla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cimpuesto)
                    .addComponent(impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csorpresa)
                    .addComponent(sorpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCasillaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cimpuesto;
    private javax.swing.JLabel cnombre;
    private javax.swing.JLabel cnumcasilla;
    private javax.swing.JLabel csorpresa;
    private javax.swing.JTextField impuesto;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numCasilla;
    private javax.swing.JTextField sorpresa;
    // End of variables declaration//GEN-END:variables
}
