/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Civitas;
import civitas.Jugador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ecast
 */
public class CivitasView extends javax.swing.JFrame {

    public Civitas juego;
    public JugadorPanel jugadorPanel;
    public CasillaPanel casillaPanel;
    public int gestionElegida;
    public int propiedadElegida;
    public GestionarDialog gestionarD;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        ContenedorVistaJugador.add(jugadorPanel);
        
        casillaPanel = new CasillaPanel();
        ContenedorVistaCasilla.add(casillaPanel);
        
        gestionarD = new GestionarDialog(this);
        
        repaint();
        revalidate();
    }
 public int getGestion(){
     //System.out.println(gestionElegida);
        return gestionarD.getGestion();
    }
    
    public int getPropiedad(){
        return gestionarD.getPropiedad();
    }
    public void actualizarVista(){
        jugadorPanel.setJugador(juego.getJugadorActual());
        int numCasilla = juego.getJugadorActual().getNumCasillaActual();
        casillaPanel.setCasilla(juego.getCasillaActual() , numCasilla);
        ranking.setVisible(false);
        cranking.setVisible(false);
        if(juego.finalDelJuego()){
            ranking.setVisible(true); //la caja que contiene el texto de rank
            cranking.setVisible(true); //la etiqueta con ranking
            ArrayList<Jugador> jugadores; 
            jugadores = juego.ranking();
            String nombres = "";
            for (Jugador j : jugadores){
                nombres = nombres + j.getNombre()+" "+ Float.toString(j.getSaldo());
                nombres = nombres + "/n";
            }
            ranking.setText(nombres); //el panel interior donde se escribe
        }
        repaint();
        revalidate();
    }
    public void mostrarEventos(){
        DiarioDialog diarioD = new DiarioDialog(this); //cera la ventana dl diario
    }
    
    public void setCivitas(Civitas civitas){
        juego = civitas;
        setVisible(true);//poner visible la vista
    }
    

    public void mostrarSiguienteOperacion(OperacionesJuego operacion){
        siguienteOp.setText(operacion.toString());
        actualizarVista();
    }
    
    public Respuestas comprar(){
        Respuestas resp = null;
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
    
        if (opcion == 0)
            resp = Respuestas.SI;
        if (opcion == 1)
            resp = Respuestas.NO;
        return resp;
    }
    
    public void gestionar(){
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
    }
    
    public SalidasCarcel salirCarcel(){
        SalidasCarcel resp= null;
        String[] opciones = {"Salir Pagando", "Salir tirando"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?", "Salir de la cárcel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if (respuesta == 0)
            resp = SalidasCarcel.PAGANDO;
        if (respuesta == 1)
            resp = SalidasCarcel.TIRANDO;
        return resp;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        ContenedorVistaJugador = new javax.swing.JPanel();
        ContenedorVistaCasilla = new javax.swing.JPanel();
        cop = new javax.swing.JLabel();
        siguienteOp = new javax.swing.JTextField();
        cranking = new javax.swing.JLabel();
        ranking = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("Civitas");
        titulo.setEnabled(false);

        cop.setText("Siguiente Operacion");
        cop.setEnabled(false);

        siguienteOp.setText("SiguienteOp");
        siguienteOp.setEnabled(false);
        siguienteOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteOpActionPerformed(evt);
            }
        });

        cranking.setText("Ranking");
        cranking.setEnabled(false);

        ranking.setText("ranking");
        ranking.setEnabled(false);
        ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ContenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContenedorVistaCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cop)
                                    .addComponent(cranking))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(siguienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(titulo)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContenedorVistaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContenedorVistaCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cop)
                            .addComponent(siguienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cranking)
                            .addComponent(ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteOpActionPerformed

    private void rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorVistaCasilla;
    private javax.swing.JPanel ContenedorVistaJugador;
    private javax.swing.JLabel cop;
    private javax.swing.JLabel cranking;
    private javax.swing.JTextField ranking;
    private javax.swing.JTextField siguienteOp;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

   
}
