/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author ecast
 */
public class PropiedadPanel extends javax.swing.JPanel {

    public TituloPropiedad tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(TituloPropiedad tit){
        tituloPropiedad = tit;
        nombre.setText(tituloPropiedad.getNombre());
        numCasas.setText(Integer.toString(tituloPropiedad.getNumCasas()));
        numHoteles.setText(Integer.toString(tituloPropiedad.getNumHoteles()));
        if(tituloPropiedad.getHipotecado())
            hipotecada.setText("SI");
        else 
            hipotecada.setText("NO");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        pnombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        pcasas = new javax.swing.JLabel();
        numCasas = new javax.swing.JTextField();
        photeles = new javax.swing.JLabel();
        numHoteles = new javax.swing.JTextField();
        phipotecada = new javax.swing.JLabel();
        hipotecada = new javax.swing.JTextField();

        titulo.setText("Propiedades:");
        titulo.setEnabled(false);

        pnombre.setText("Nombre");
        pnombre.setEnabled(false);

        nombre.setText("Nombre");
        nombre.setEnabled(false);

        pcasas.setText("Numero de casas");
        pcasas.setEnabled(false);

        numCasas.setText("numero de casas");
        numCasas.setEnabled(false);

        photeles.setText("Numero de hoteles");
        photeles.setEnabled(false);

        numHoteles.setText("Numero de hoteles");
        numHoteles.setEnabled(false);

        phipotecada.setText("¿Está Hipotecada?");
        phipotecada.setEnabled(false);

        hipotecada.setText("si/no");
        hipotecada.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pcasas)
                            .addComponent(pnombre)
                            .addComponent(photeles)
                            .addComponent(phipotecada))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcasas)
                    .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photeles)
                    .addComponent(numHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phipotecada)
                    .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hipotecada;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numCasas;
    private javax.swing.JTextField numHoteles;
    private javax.swing.JLabel pcasas;
    private javax.swing.JLabel phipotecada;
    private javax.swing.JLabel photeles;
    private javax.swing.JLabel pnombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
